#!/usr/bin/env python
"""
shana2 - an over engineered, phenny semi-compatible Python 3 IRC bot
Copyright 2013, icecapsol@gmail.com

Large chunks of code derived from phenny

Copyright 2008, Sean B. Palmer, inamidst.com
Licensed under the Eiffel Forum License 2.
http://inamidst.com/phenny/
"""

import sys, os, re, time, imp, datetime, traceback, getopt, signal, locale
import yaml
from multiprocessing import Process, Pipe, Queue

class Letter:
	def __init__(self,to, subject, body, sender=None):
		self.sender = sender
		self.to = to
		self.to_f = to.split('.')
		self.subject = subject
		self.body = body

class Event():
	def __init__(self, text, data, bytes, event, args, config):
		#s = str.__new__(cls, text)
		self.sender = data['sender']
		self.nick = data['nick']
		self.host = data['host']
		self.user = data['user']
		self.event = event
		self.bytes = bytes
		self.match = None
		self.search = None
		self.searches = None
		self.group = None #match.group
		self.groups = None #match.groups
		self.args = args
		self.admin = self.nick in config['groups']['admin']
		self.owner = self.nick == config['groups']['sysop']
		if self.nick.lower() in config['passwd']:
			self.username = self.nick.lower()
		else:
			self.username = 'nobody'
		self.ugroups = config['passwd'].get(self.username, ['nobody'])

class Launcher():
	def __init__(self, conf_name):
		self.inbox, self.box_r = Pipe()
		self.outbox = Queue(16386) # PO's inbox
		self.running = {}
		signal.signal(signal.SIGINT, self.die)
		self.locale_check()
		self.conf_name = conf_name
		self.read_config()
		self.load_modules()
		self.startup()
		self.run()
	
	def read_config(self):
		conf_file = open(self.conf_name, "r")
		self.config = yaml.load(conf_file)
		conf_file.close()
	def write_config(self):
		os.rename(self.conf_name, self.conf_name+".sav")
		conf_file = open(self.conf_name, "w")
		yaml.dump(self.config, conf_file, default_flow_style=False)
		conf_file.close()
	def reload_config(self, config):
		self.config = config
		self.load_modules()
	def merge(self, x,y):        
		merged = dict(list(x.items()) + list(y.items()))
		xkeys = x.keys()
	                      
		for key in xkeys:                               
			if str(type(x[key])) == "<class 'dict'>" and key in y.keys():
				merged[key] = self.merge(x[key],y[key])
		return merged
	
	def locale_check(self):
		if locale.getpreferredencoding() != "UTF-8":
			self.log("Default encoding is not set to UTF-8. This will likely break unicode support.", "CRITICAL")
	
	def die(self, sig, frame):
		sys.exit(0)
	
	def load_module(self, fn):
		mod = Module(fn, self.merge(self.config.get("Modules", {}), self.merge(self.config["Global"], self.config.get("Module.%s" % fn.rpartition(".")[0], {}))))
		for m in self.modules:
			if m.name == mod.name:
				self.modules.remove(m)
		self.modules.append(mod)

	def load_modules(self):
		self.modules = []
		exceptions = []
		for fn in [fn for fn in os.listdir("modules") if os.path.isfile("modules/"+fn) and not fn.startswith("_") and fn.endswith(".py")]:
			try: self.load_module(fn)
			except:
				trace = traceback.format_exc()
				print(trace)
				exceptions.append(fn)
		self.log("Loaded %d modules (%d errors)" % (len(self.modules), len(exceptions)), "NOTICE")
	
	def launch_module(self, mod, func, event=None):
		q = Pipe()
		p = Process(target=mod.start, args=(event, func, (q[0], self.outbox), mod.name))
		p.start()
		self.send("self.post office", "Add", {'name': "module.%s.%s.%s" % (mod.name, func.name, p.pid), "queue": q[1]})
		self.log("Launching module %s.%s.%s" % (mod.name, func.name, p.pid), "STATUS")
		func.last_launched = time.time()
		return p
	
	def startup(self):
		# Post office
		self.pobox = Postoffice(self.outbox, dict(list(self.config.get("Post Office", {}).items()) + list(self.config["Global"].items())))
		p = Process(target=self.pobox.run, args=())
		p.start()
		self.send("self.post office", "Add", {'name': "self.launcher.%s" % p.pid, "queue": self.box_r})
		self.log("Starting post office", "NOTICE")
		
		for m in self.modules:
			for func in m.functions:
				if func.startup:
					self.log("Launching startup module %s." % func.name, "STATUS")
					self.launch_module(m, func, None)

	def send(self, to, subject, body):
		l = Letter(to, subject, body, "self.launcher")
		self.outbox.put(l)
	
	def log(self, line, level):
		self.send("module.bot.logger", "LOG", {'module': 'Launcher', 'time': int(time.time()), 'text': line, 'level': level})
	
	def shutdown(self, args):
		sys.exit(0)
	
	def get_module_function(self, name):
		if isinstance(name, list) or isinstance(name, tuple):
			try: module_class, module_name, function_name = name
			except: return (None, None)
		else:
			try: module_class, module_name, function_name = name.split(".")
			except: return (None, None)
		try:
			module = [mod for mod in self.modules if mod.name == module_name][0]
			function = [func for func in module.functions if func.name == function_name][0]
			return (module, function)
		except:
			return (None, None)
	
	def run(self):
		while True:
			letter = self.inbox.recv()
			if letter.subject == "NEW EVENT":
				event = letter.body['event']
				for m in self.modules:
					for func in m.trigger(event):
						if func.service:
							self.send("module.%s.%s" % (m.name, func.name), "NEW EVENT", {'event': event, 'modname': m.name, 'funcname': func.name, 'service': True})
						else:
							self.launch_module(m, func, event)
			elif letter.subject == "WAKE":
				mod, func = self.get_module_function(letter.body['letter'].to_f[:3])
				if not func:
					self.send("self.post office", "WAKE FAIL", {'letter': letter.body['letter']})
					self.log("Bad WAKE event %s" % letter.body['letter'].to, "ERROR")
					continue

				self.launch_module(mod, func)
				self.outbox.put(letter.body['letter'])

			elif letter.subject == "RELOAD MODULE":
				for name in letter.body['names']:
					if os.path.isfile("modules/"+name+".py"):  # RFI
						try:
							self.load_module(name+".py")
							self.send("module.bot.communicator", "NEW IRC OUTPUT", {'message': "PRIVMSG %s :%s: modules.%s (version: %s)\r\n" % (letter.body['sender'], letter.body['nick'], name+".py", datetime.datetime.now())})
						except Exception as e:
							self.send("module.bot.communicator", "NEW IRC OUTPUT", {'message': "PRIVMSG %s :%s: Error loading module %s: %s\r\n" % (letter.body['sender'], letter.body['nick'], name+".py", e)})
					else:
						self.send("module.bot.communicator", "NEW IRC OUTPUT", {'message': "PRIVMSG %s :%s: Error loading module %s: file doesn't exist\r\n" % (letter.body['sender'], letter.body['nick'], name+".py")})
			elif letter.subject == "LIST MODULES":
				mods = {}
				for mod in self.modules:
					mods[mod.name] = [func.name for func in mod.functions]
				self.send(letter.sender, "MODULES LIST", {'list': mods})
			elif letter.subject == "RELOAD CONF":
				self.reload_config(self.merge(self.config, letter.body['config']))
				self.log("Reloaded configuration", "NOTICE")
			elif letter.subject == "SHUTDOWN":
				if not letter.sender == "self.post office": continue
				self.shutdown()

class Postoffice():
	def __init__(self, queue, config):
		self.reload_config(config)
		self.inbox = queue
		self.boxes = {}
		self.hold = {}
		signal.signal(signal.SIGINT, self.die)
	
	def reload_config(self, config):
		self.config = config
		
	def die(self, sig, frame):
		sys.exit(0)
	
	def mkbox(self, box_name, queue):
		names = self.best_match(box_name)
		if names:
			print("POST OFFICE: Error adding outbox for %s. Name exists" % box_name)
			return None
		self.boxes[box_name] = {"sock": queue}
		return self.boxes[box_name]
	
	def rmbox(self, box_name):
		names = self.best_match(box_name)
		if not names:
			print("POST OFFICE: No outbox for %s." % box_name)
			return False
		try: self.boxes[names[0]]['sock'].send(Letter(name, "LAST LETTER", {}, "self.post office"))
		except: pass
		del self.boxes[names[0]]
		return True

	def process(self, letter):
		if letter.subject == "Add":
			new_box = self.mkbox(letter.body['name'], letter.body["queue"])
			for name, waiting in list(self.hold.items())[:]:
				if name in letter.body['name']:
					for letter in waiting:
						new_box['sock'].send(letter)
					del self.hold[name]
		elif letter.subject == "REMOVE":
			self.rmbox(letter.body['name'])
		elif letter.subject == "RELOAD":
			self.reload_config(letter.body['config'])
		elif letter.subject == "LIST BOXES":
			names = self.best_match(letter.sender)
			try: self.boxes[names[0]]['sock'].send(Letter(letter.sender, "LIST BOXES", {'list': list(self.boxes.keys())}, "self.post office"))
			except: pass
		elif letter.subject == "WAKE FAIL":
			l = letter.body['letter']
			names = self.best_match(l.sender)
			if names: # relabel the subject and send it back
				l.body['RTS'] = l.subject
				l.subject = "RETURN TO SENDER"
				self.boxes[names[0]]['sock'].send(l)
			for name in list(self.hold.keys()): # delete the hold
				if name in l.to:
					del self.hold[name]
	
	def best_match(self, name):
		match = re.compile(re.escape(name)+".*")
		return [match.match(bname).group() for bname in self.boxes.keys() if match.match(bname)]
	
	def run(self):
		while True:
			letter = self.inbox.get()
			
			if letter.to == "self.post office":
				self.process(letter)
				continue

			names = self.best_match(letter.to)

			if names:
				for name in names:
					self.boxes[name]['sock'].send(letter)
			elif letter.to in self.hold.keys(): # store it if we're waiting for it to wake up
				self.hold[letter.to].append(letter)
			else: # there's no hold, wake the module up
				names = self.best_match("self.launcher")
				if not names:
					self.inbox.put(letter)
					time.sleep(0.01)
					continue

				# it's ok to send to multiple launchers
				for name in names:
					self.boxes[name]['sock'].send(Letter("self.launcher", "WAKE", {"letter": letter}))

				# now that we are waiting for the module to wake up, save the letter
				self.hold[letter.to] = [letter,]

class ACL():
	def __init__(self, module):
		self.owner = getattr(module, 'owner', 'nobody')
		self.group = getattr(module, 'group', 'nobody')
		if self.owner == 'nobody' or self.group == 'nobody':
			self.owner, self.group = ('nobody', 'nobody')
			self.mode = ((True, True), (True, True), (True, True))
		else:
			self.mode = getattr(module, 'mode', ((True, True), (True, False), (True, False))) # execute, modify
		self.funcs = {}

class Module():
	class Function():
		def __init__(self, name, func, config):
			def sub(pattern, self=self):
				# These replacements have significant order
				pattern = pattern.replace('$nickname', config['name'])
				return pattern.replace('$nick', r'%s[,:] +' % config['name'])
			self.name = name
			self.func = func
			self.rule = getattr(self.func, 'rule', [])
			self.commands = getattr(self.func, 'commands', [])
			self.startup = getattr(self.func, 'startup', False)
			self.service = getattr(self.func, 'service', False)
			quota = getattr(self.func, 'quota', (0, 0, 0))
			if isinstance(quota, int) or isinstance(quota, float):
				quota = (self.func.quota, self.func.quota, self.func.quota)
			self.quota = quota
			self.last_launched = 0
			if hasattr(self.func, "event"):
				if isinstance(self.func.event, str):
					self.event = [self.func.event,]
				else:
					self.event = self.func.event
			else:
				self.event = getattr(self.func, 'event', ['PRIVMSG'])
			#print(self.event)
			if self.rule:
				if isinstance(self.rule, str): 
					pattern = sub(self.rule)
					regexp = re.compile(pattern)
					self.rule = [regexp]

				if isinstance(func.rule, tuple): 
					# 1) e.g. ('$nick', '(.*)')
					if len(self.rule) == 2 and isinstance(self.rule[0], str): 
						prefix, pattern = self.rule
						prefix = sub(prefix)
						regexp = re.compile(prefix + pattern)
						self.rule = [regexp]

					# 2) e.g. (['p', 'q'], '(.*)')
					elif len(self.rule) == 2 and isinstance(self.rule[0], list): 
						prefix = config['prefix']
						commands, pattern = self.rule
						self.rule = []
						for command in commands: 
							command = r'(%s)(?: +(?:%s))?' % (command, pattern)
							regexp = re.compile(prefix + command)
							self.rule.append(regexp)

					# 3) e.g. ('$nick', ['p', 'q'], '(.*)')
					elif len(self.rule) == 3: 
						prefix, commands, pattern = self.rule
						prefix = sub(prefix)
						self.rule = []
						for command in commands: 
							command = r'(%s) +' % command
							regexp = re.compile(prefix + command + pattern)
							self.rule.append(regexp)

			if self.commands:
				c = []
				for command in self.commands: 
					template = r'^%s(%s)(?: +(.*))?$'
					pattern = template % (config['prefix'], command)
					regexp = re.compile(pattern)
					c.append(regexp)
				self.commands = c
	class Bot():
		def __init__(self, mail, event, name, pid, conf):
			self.inbox = mail[0]
			self.outbox = mail[1]
			self.letters = []
			self.name = '.'.join(name)
			self.input = event
			self.pid = pid
			self.conf = conf
			self.handlers = {'subject': {}, 'sender': {}}
		def write(self, args, text=None):
			def safe(data): 
				data = data.replace('\n', '')
				data = data.replace('\r', '')
				return data
			args = [safe(arg) for arg in args]
			if text is not None:
				text = safe(text)
				self.send("module.bot.communicator", "NEW IRC OUTPUT", {'message': ' '.join(args) + ' :' + text + '\r\n'})
			else: self.send("module.bot.communicator", "NEW IRC OUTPUT", {'message': ' '.join(args) + '\r\n'})

		def msg(self, recipient, text):
			self.write(('PRIVMSG', recipient), text)
		def say(self, text):
			self.msg(self.input.sender, text)
		def reply(self, text):
			self.msg(self.input.sender, "%s: %s" % (self.input.nick, text))
		def send(self, to, subject, body):
			l = Letter(to, subject, body, self.name)
			self.outbox.put(l)
		def log(self, line, level):
			self.send("module.bot.logger", "LOG", {'module': self.name, 'time': int(time.time()), 'text': line, 'level': level})
		def register(self, func, subject=None, sender=None):
			if subject:
				if isinstance(subject, str):
					h = self.handlers['subject'].setdefault(subject, [])
					h.append(func)
					self.handlers['subject'][subject] = h
				else:
					for subj in subject:
						h = self.handlers['subject'].setdefault(subj, [])
						h.append(func)
						self.handlers['subject'][subj] = h
			if sender:
				if isinstance(sender, str):
					h = self.handlers['sender'].setdefault(sender, [])
					h.append(func)
					self.handlers['sender'][sender] = h
				else:
					for send in sender:
						h = self.handlers['sender'].setdefault(send, [])
						h.append(func)
						self.handlers['sender'][send] = h
		def loop(self):
			def callback(funcs, letter):
				for func in funcs:
					try: func(letter)
					except Exception as e:
						self.log("Exception in callback %s: %s" % (func.__name__, e), "ERROR")

			while True:
				l = self.recv()
				hits = [self.handlers['subject'][hit] for hit in self.handlers['subject'].keys() if hit == l.subject]
				hits.extend([self.handlers['sender'][hit] for hit in self.handlers['sender'].keys() if hit == l.sender])
				
				for hit in hits:
					callback(hit, l)
		def recv(self, subject=None, sender=None, block=True):
			while self.inbox.poll():
				self.letters.append(self.inbox.recv())
			if subject or sender:
				while True:
					if len(self.letters) == 0: self.letters.append(self.inbox.recv())
					if subject:
						matches = [mletter for mletter in self.letters if len([True for filt in subject if re.match(filt, mletter.subject)]) > 0]
						if len(matches) == 0 and block: continue
						elif len(matches) > 0:
							self.letters.remove(matches[0])
							return matches[0]
						else: return None
					elif sender:
						matches = [mletter for mletter in self.letters if len([True for filt in sender if re.match(filt, mletter.sender)]) > 0]
						if len(matches) == 0 and block: continue
						elif len(matches) > 0:
							self.letters.remove(matches[0])
							return matches[0]
						else: return None
			else:
				if len(self.letters) > 0:
					return self.letters.pop(0)
				elif block and len(self.letters) == 0:
					return self.inbox.recv()
				else:
					return None
				
		def discard(self, timeout=1):
			if self.inbox.poll(timeout):
				self.inbox.recv()
				return 1
			else:
				return 0
		
	def __init__(self, name, config):
		self.config = config
		module = getattr(__import__('modules.' + name.rpartition(".")[0]), name.rpartition(".")[0])
		imp.reload(module)
		self.name = name.rpartition(".")[0]
		self.functions = []
		self.acl = ACL(module)
		for name, func in vars(module).items():
			if not str(type(func)) == "<class 'function'>": continue
			fname = getattr(func, 'name', name)
			self.functions.append(Module.Function(fname, func, config))
			self.acl.funcs[fname] = {'owner': getattr(func, 'owner', 'nobody'), 
							    'group': getattr(func, 'group', 'nobody'), 
							    'priority': getattr(func, 'priority', 'low'), 
							    'mode': getattr(module, 'mode', (True, True, True))}
	
	def trigger(self, event):
		launch = []
		for func in self.functions:
			if event.event in func.event and ([True for regexp in func.rule if regexp.match(event.bytes)] or [True for regexp in func.rule if regexp.search(event.bytes)] or [True for regexp in func.commands if regexp.match(event.bytes)]) and self.approve(func, event):
				launch.append(func)
		return launch
	def approve(self, func, event):
		acl = self.acl.funcs[func.name]
		if acl['mode'][2] or (acl['group'] in event.ugroups and acl['mode'][1]) or (event.username == acl['owner'] and acl['mode'][0]):
			if (event.username == acl['owner'] and func.last_launched + func.quota[0] < time.time()) or (
			   acl['group'] in event.ugroups and func.last_launched + func.quota[1] < time.time()) or (
			   func.last_launched + func.quota[2] < time.time()):
				return True

	def start(self, event, func, mail, mod_name):
		if hasattr(os, 'getppid'):
			pid = os.getppid()
		else:
			pid = os.getpid()
		bot = Module.Bot(mail, event, ["module", self.name, func.name], pid, self.config)
		if event and hasattr(event, "bytes"):
			if func.commands:
				for command in func.commands:
					match = command.match(event.bytes)
					if match:
						event.match = match
						event.group = match.group
						event.groups = match.groups
			elif func.rule:
				for rule in func.rule:
					match = rule.match(event.bytes)
					if match:
						event.match = match
						event.group = match.group
						event.groups = match.groups
					search = rule.search(event.bytes)
					if search:
						event.search = search
						event.searches = rule.findall(event.bytes)
			else:
				event.match = None
				event.group = None
				event.groups = None

		#for lim, val in func.limits.items():
			#resource.setrlimit(lim, val)
		try: func.func(bot, event)
		except KeyboardInterrupt:
			pass
		except:
			trace = traceback.format_exc()
			for line in trace.split('\n'):
				bot.log(line, "ERROR")
			lines = list(reversed(trace.splitlines()))
			report = [lines[0].strip()]
			for line in lines: 
				line = line.strip()
				if line.startswith('File "/'): 
					report.append(line[0].lower() + line[1:])
					break
			else: report.append('source unknown')
			try: bot.say(report[0] + ' (' + report[1] + ')')
			except: pass # services have no event!
		try: bot.send("self.post office", "REMOVE", {'name': "module.%s.%s" % (mod_name, func.name)})
		except: pass

conf_name = "shana2.conf"

optlist, args = getopt.getopt(sys.argv[1:], 'c:', ['conf',])

for opt in optlist:
    if opt[0] in ['-c', '--conf']:
        conf_name = opt[1]

Launcher(conf_name)
